version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_sm_db
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: social_media
      MYSQL_USER: ihsan
      MYSQL_PASSWORD: qwerty
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
